[package]
name = "rust-repro"
version = "0.1.0"
authors = ["Brandon Arp <brandonarp@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = { version="0.7", features=["ssl"] }
futures = "0.1"
log = "0.4.6"
log4rs = "0.8.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
